---

jobs:

  - job: build_macos
    displayName: Build on macOS
    pool:
      vmImage: macos-10.13
    steps:
      - template: ci/all.yaml


  - job: build_linux
    displayName: Build on Ubuntu 16.04
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/all.yaml
