---

jobs:

  - job: build_macos
    displayName: Build on macOS
    condition: and(succeeded(), not(variables.task), eq(variables.os, 'Darwin'))
    pool:
      vmImage: macos-10.13
    steps:
      - template: ci/all.yaml


  - job: build_linux
    displayName: Build on Ubuntu 16.04
    condition: and(succeeded(), not(variables.task), eq(variables.os, 'Darwin'))
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/all.yaml
