steps:

- task: ShellScript@2
  inputs:
    scriptPath: 'scripts/setup.sh'
   displayName: 'Set up build environment'

- task: ShellScript@2
  inputs:
    scriptPath: 'scripts/lint.sh'
  displayName: 'Lint'

- task: ShellScript@2
  inputs:
    scriptPath: 'scripts/build.sh'
  displayName: 'Build'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: "**/TEST-*.xml"

